# Generated by Django 4.2.1 on 2023-05-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('options', models.JSONField()),
                ('right_answer', models.IntegerField()),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('finished', 'Finished')], default='inactive', max_length=10)),
            ],
        ),
    ]
